/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function createDeltaFile(source: string, target: string, delta: string, window: number, prime: number): void
export function createTargetFile(source: string, target: string, delta: string): void
